version: '2'
services:
  sympa:
    container_name: centos_sympa
    image: project42/centos_sympa
    ports:
       - 80:80
       - 25:25
    volumes:
      - ~/sympadata/sympaspool:/var/spool/sympa
      - ~/sympadata/postfixspool:/var/spool/postfix
      - ~/sympadata/sympaetc:/etc/sympa
      - ~/sympadata/sympalib:/var/lib/sympa
    restart: always
    environment:
      - SYMPA_DOMAIN=lists.hallhome.private
      - SYMPA_LISTMASTERS=rance.hall@esu10.org
      - SYMPA_POSTFIX_RELAY=services.hallhome.private
      - SYMPA_DB_TYPE=mysql
      - SYMPA_DB_HOST=services.hallhome.private
      - SYMPA_DB_USER=sympa
      - SYMPA_DB_PASS=sympa
      - SYMPA_DB_NAME=sympa
