#!/bin/sh

# run health check to setup and maintain db
/usr/sbin/sympa.pl --health_check

#check for and create domain level sympa aliases and potentially run data import.

if [ ! -e /etc/domain_aliases]; then
  cat /etc/sympa/aliases.sympa.postfix > /var/lib/sympa/sympa_aliases
  touch /etc/domain_aliases
fi
