#!/bin/sh

/bin/s6-svc -u /etc/services.d/rsyslog
/bin/s6-svwait -u /etc/services.d/rsyslog
/bin/s6-svc -u /etc/services.d/nginx
/bin/s6-svc -u /etc/services.d/postfix
/bin/s6-svc -u /etc/services.d/sympa-msg
/bin/s6-svwait -u /etc/services.d/sympa-msg
/bin/s6-svc -u /etc/services.d/sympa-archive
/bin/s6-svc -u /etc/services.d/sympa-bounce
/bin/s6-svc -u /etc/services.d/sympa-bulk
/bin/s6-svc -u /etc/services.d/sympa-task
/bin/s6-svc -u /etc/services.d/sympa-fcgi
