#!/bin/sh

# run health check to setup and maintain db
/usr/sbin/sympa.pl --health_check

#check for and create domain level sympa aliases and potentially run data import.

if [ ! -e /etc/sympa/domain_aliases ]; then
  cat /etc/sympa/aliases.sympa.postfix > /var/lib/sympa/sympa_aliases
  postalias /var/lib/sympa/sympa_aliases
  postalias /etc/aliases
  mv /keep/sympalib/transport_regexp.new /var/lib/sympa/transport_regexp
  postmap /var/lib/sympa/transport_regexp
  touch /etc/sympa/domain_aliases
fi

#if [ ! -e /etc/domain_migrated ]; then

  #touch /etc/domain_migrated
#fi
